### PR TITLE
Addbio

### PR DESCRIPTION
**Pull request by KafkaNoNeko**
I have tried to follow the format in the example.  Is this good enough?

### CODE REVIEW

**Comment by firasm** [comment]
Looks great! Thanks for getting this started. One request: Could you re-sort all the undergrad students alphabetically by their last name? So the order would be: myself, Stephen, Michael, Graham, Abby, etc...

After that, we can merge it in!

**Review by firasm — CHANGES_REQUESTED** [review]
Looks great! Thanks for doing this. 

One request: let's add some headings. 

1. Add Level 2 headers "## Principal Investigator", "## Graduate students", "## Undergraduate students"
2. Then, could you sort everyone alphabetically by last name under each heading?

**Comment by KafkaNoNeko** [comment]
Done!

1. I sorted everyone alphabetically but did not place the last name first for consistency.  Please let me know if this needs to be changed.

2. Would you like the project title to be changed to "next generation problem bank"?

3. Do we already know what everyone's preferred email address is?  If not, I can ask!  In addition, would having a link to everyone's LinkedIn be a desirable feature as well?  

(Also, I made the placeholder image myself so there should not be any copyright issue)

**Review by firasm — APPROVED** [review]
Awesome, thanks!!

**Pull request merged**
